// server/data/products.js — Alpha Furniture Product Catalogue with real images

const products = [
  // ── DINING TABLES ─────────────────────────────────────────────────────────
  {
    id: "ALF-D01", name: "Luxury Royal Carved Dining Set", slug: "luxury-royal-carved-dining",
    category: "dining", subcategory: "Dining Sets",
    price: 185000, originalPrice: 220000, badge: "Sale",
    inStock: true, stockQty: 3, rating: 5, reviewCount: 47, isFeatured: true, isNew: false,
    description: "Exquisite 8-seater royal dining set with hand-carved sheesham wood frame and premium white/gold upholstered chairs. A centrepiece fit for a palace.",
    colors: [{ name: "Walnut & Gold", hex: "#8B6914" }],
    specifications: { Material: "Solid Sheesham Wood", Seating: "8 Persons", Dimensions: "240 × 100 × 78 cm", Upholstery: "Premium Fabric", Finish: "Walnut & Gold", Warranty: "2 Years" },
    images: ["/images/dining/dining-luxury-carved.png"],
  },
  {
    id: "ALF-D02", name: "Glass Top Wooden Dining Set", slug: "glass-top-wooden-dining",
    category: "dining", subcategory: "Dining Sets",
    price: 72000, originalPrice: 88000, badge: "Sale",
    inStock: true, stockQty: 6, rating: 4, reviewCount: 31, isFeatured: true, isNew: false,
    description: "Modern 4-seater dining set with tempered glass top and solid dark wood frame. Clean contemporary design that suits any dining room.",
    colors: [{ name: "Dark Walnut", hex: "#3E2723" }],
    specifications: { Material: "Sheesham Wood + Tempered Glass", Seating: "4 Persons", Dimensions: "140 × 80 × 76 cm", Warranty: "2 Years" },
    images: ["/images/dining/dining-glass-wooden.png"],
  },
  {
    id: "ALF-D03", name: "White & Golden Dining Set", slug: "white-golden-dining",
    category: "dining", subcategory: "Dining Sets",
    price: 145000, originalPrice: 175000, badge: "Sale",
    inStock: true, stockQty: 4, rating: 5, reviewCount: 38, isFeatured: true, isNew: false,
    description: "Elegant 6-seater dining set in white and gold finish with premium dark upholstered chairs. Timeless luxury for your dining room.",
    colors: [{ name: "White & Gold", hex: "#C8A532" }],
    specifications: { Material: "MDF + Solid Wood", Seating: "6 Persons", Dimensions: "200 × 90 × 78 cm", Upholstery: "Dark Velvet", Warranty: "2 Years" },
    images: ["/images/dining/dining-white-golden.png"],
  },
  {
    id: "ALF-D04", name: "Deco Paint Dining Table", slug: "deco-paint-dining",
    category: "dining", subcategory: "Dining Sets",
    price: 55000, originalPrice: 0, badge: "New",
    inStock: true, stockQty: 8, rating: 4, reviewCount: 14, isFeatured: false, isNew: true,
    description: "Unique 4-seater dining set featuring a stunning hand-painted deco top with intricate floral motifs. A true statement piece.",
    colors: [{ name: "Dark Wood & Deco", hex: "#3E2723" }],
    specifications: { Material: "Sheesham Wood", Seating: "4 Persons", Top: "Hand-painted Deco", Warranty: "2 Years" },
    images: ["/images/dining/dining-deco-paint.png"],
  },
  {
    id: "ALF-D05", name: "Vintage Blue Luxury Dining", slug: "vintage-blue-luxury-dining",
    category: "dining", subcategory: "Dining Sets",
    price: 225000, originalPrice: 270000, badge: "Sale",
    inStock: true, stockQty: 2, rating: 5, reviewCount: 22, isFeatured: true, isNew: false,
    description: "Ultra-luxurious 6-seater dining set with ornate carved gold frame and premium blue velvet chairs. A masterpiece of craftsmanship.",
    colors: [{ name: "Gold & Blue", hex: "#1A237E" }],
    specifications: { Material: "Solid Wood + Gold Leaf", Seating: "6 Persons", Upholstery: "Blue Velvet", Warranty: "2 Years" },
    images: ["/images/dining/dining-vintage-blue.png"],
  },
  {
    id: "ALF-D06", name: "Wooden Round Dining Set", slug: "wooden-round-dining",
    category: "dining", subcategory: "Dining Sets",
    price: 68000, originalPrice: 82000, badge: "Sale",
    inStock: true, stockQty: 5, rating: 4, reviewCount: 19, isFeatured: false, isNew: false,
    description: "Compact 4-seater dining set with inlaid wooden round table top and cushioned stools. Perfect for smaller dining spaces.",
    colors: [{ name: "Dark Walnut", hex: "#3E2723" }],
    specifications: { Material: "Sheesham Wood", Seating: "4 Persons", Shape: "Round", Warranty: "2 Years" },
    images: ["/images/dining/dining-round-wooden.png"],
  },
  {
    id: "ALF-D07", name: "Comfy Cream Dining Set", slug: "comfy-cream-dining",
    category: "dining", subcategory: "Dining Sets",
    price: 115000, originalPrice: 138000, badge: "Sale",
    inStock: true, stockQty: 4, rating: 5, reviewCount: 33, isFeatured: true, isNew: false,
    description: "Sophisticated 6-seater dining set with inlaid wood table top and luxurious cream upholstered barrel chairs. Premium comfort meets style.",
    colors: [{ name: "Walnut & Cream", hex: "#EDE0C8" }],
    specifications: { Material: "Sheesham Wood", Seating: "6 Persons", Upholstery: "Cream Fabric", Warranty: "2 Years" },
    images: ["/images/dining/dining-comfy-cream.png"],
  },

  // ── BEDS ──────────────────────────────────────────────────────────────────
  {
    id: "ALF-B01", name: "Horn Grey Luxury Bed", slug: "horn-grey-luxury-bed",
    category: "beds", subcategory: "King Beds",
    price: 95000, originalPrice: 115000, badge: "Sale",
    inStock: true, stockQty: 5, rating: 5, reviewCount: 42, isFeatured: true, isNew: false,
    description: "Stunning king-size bed in grey velvet with unique horn-shaped headboard detail and gold accents. Includes matching side tables and dressing.",
    colors: [{ name: "Grey & Gold", hex: "#9E9E9E" }],
    specifications: { Material: "Velvet + MDF", Size: "King", Headboard: "Horn Design", Includes: "Side Tables + Dressing", Warranty: "2 Years" },
    images: ["/images/beds/bed-horn-grey.png"],
  },
  {
    id: "ALF-B02", name: "Pure Wooden Bedroom Set", slug: "pure-wooden-bedroom-set",
    category: "beds", subcategory: "Queen Beds",
    price: 78000, originalPrice: 95000, badge: "Sale",
    inStock: true, stockQty: 7, rating: 4, reviewCount: 28, isFeatured: true, isNew: false,
    description: "Classic solid wood bedroom set in honey oak with natural grain finish. Includes bed, wardrobe, and side tables. Built to last generations.",
    colors: [{ name: "Honey Oak", hex: "#C8A030" }],
    specifications: { Material: "Solid Sheesham Wood", Size: "Queen", Includes: "Bed + Wardrobe + Side Tables", Finish: "Honey Oak", Warranty: "2 Years" },
    images: ["/images/beds/bed-pure-wooden.png"],
  },
  {
    id: "ALF-B03", name: "Empire Luxury Bed Set", slug: "empire-luxury-bed-set",
    category: "beds", subcategory: "King Beds",
    price: 125000, originalPrice: 150000, badge: "Sale",
    inStock: true, stockQty: 4, rating: 5, reviewCount: 55, isFeatured: true, isNew: false,
    description: "Regal empire-style king bed in dark walnut with gold trim, padded headboard, and full bedroom set including matching dresser and side tables.",
    colors: [{ name: "Dark Walnut & Gold", hex: "#3E2723" }],
    specifications: { Material: "Sheesham Wood + Velvet", Size: "King", Includes: "Full Bedroom Set", Finish: "Dark Walnut + Gold", Warranty: "2 Years" },
    images: ["/images/beds/bed-empire-set.png"],
  },
  {
    id: "ALF-B04", name: "Deco Golden Bed", slug: "deco-golden-bed",
    category: "beds", subcategory: "King Beds",
    price: 88000, originalPrice: 105000, badge: "Sale",
    inStock: true, stockQty: 6, rating: 5, reviewCount: 36, isFeatured: true, isNew: false,
    description: "Contemporary king bed with brushed gold finish, ribbed headboard with decorative tree motif. Includes matching side tables and mirror.",
    colors: [{ name: "Brushed Gold", hex: "#C8A532" }],
    specifications: { Material: "MDF + Gold Finish", Size: "King", Headboard: "Ribbed with Tree Design", Warranty: "2 Years" },
    images: ["/images/beds/bed-deco-golden.png"],
  },
  {
    id: "ALF-B05", name: "Forest Bed Set", slug: "forest-bed-set",
    category: "beds", subcategory: "King Beds",
    price: 82000, originalPrice: 98000, badge: "Sale",
    inStock: true, stockQty: 5, rating: 4, reviewCount: 24, isFeatured: false, isNew: false,
    description: "Modern king bed with geometric gold line headboard in dark wood, featuring clean architectural lines and a complete matching bedroom set.",
    colors: [{ name: "Dark Wood & Gold", hex: "#3E2723" }],
    specifications: { Material: "Sheesham Wood", Size: "King", Includes: "Bed + Dresser + Side Tables", Warranty: "2 Years" },
    images: ["/images/beds/bed-forest.png"],
  },
  {
    id: "ALF-B06", name: "White Moon Bed Set", slug: "white-moon-bed-set",
    category: "beds", subcategory: "King Beds",
    price: 145000, originalPrice: 175000, badge: "Sale",
    inStock: true, stockQty: 3, rating: 5, reviewCount: 41, isFeatured: true, isNew: false,
    description: "Opulent white moon-style king bed with dramatic fan headboard and gold ornaments. A royal statement bedroom set with full dressing mirrors.",
    colors: [{ name: "Cream & Gold", hex: "#EDE0C8" }],
    specifications: { Material: "Solid Wood + Gold Leaf", Size: "King", Style: "Royal / Ornate", Includes: "Full Bedroom Set", Warranty: "2 Years" },
    images: ["/images/beds/bed-white-moon.png"],
  },
  {
    id: "ALF-B07", name: "Black & White Classic Bed", slug: "black-white-classic-bed",
    category: "beds", subcategory: "Queen Beds",
    price: 65000, originalPrice: 78000, badge: "Sale",
    inStock: true, stockQty: 8, rating: 4, reviewCount: 29, isFeatured: false, isNew: false,
    description: "Sleek black and white queen bed with minimalist padded headboard. Complete set includes matching dresser with mirror and bedside tables.",
    colors: [{ name: "Black & White", hex: "#212121" }, { name: "Pure White", hex: "#FAFAFA" }],
    specifications: { Material: "MDF + Fabric", Size: "Queen", Finish: "Black & White", Includes: "Full Set", Warranty: "2 Years" },
    images: ["/images/beds/bed-black-white.png"],
  },
  {
    id: "ALF-B08", name: "Kasoori Wood Bed Set", slug: "kasoori-wood-bed-set",
    category: "beds", subcategory: "King Beds",
    price: 98000, originalPrice: 118000, badge: "Sale",
    inStock: true, stockQty: 4, rating: 5, reviewCount: 37, isFeatured: true, isNew: false,
    description: "Traditional kasoori-style dark wood king bed with carved headboard. Rich dark walnut finish with full matching bedroom suite.",
    colors: [{ name: "Dark Walnut", hex: "#3E2723" }],
    specifications: { Material: "Solid Sheesham Wood", Size: "King", Style: "Traditional", Includes: "Full Bedroom Suite", Warranty: "2 Years" },
    images: ["/images/beds/bed-kasoori-wood.png"],
  },
  {
    id: "ALF-B09", name: "Golden Luxury Bed Set", slug: "golden-luxury-bed-set",
    category: "beds", subcategory: "King Beds",
    price: 185000, originalPrice: 225000, badge: "Sale",
    inStock: true, stockQty: 2, rating: 5, reviewCount: 48, isFeatured: true, isNew: false,
    description: "Magnificent all-gold ornate king bed set with fan sunburst headboard, matching dressing mirrors and side tables. The ultimate luxury statement.",
    colors: [{ name: "Pure Gold", hex: "#C8A532" }],
    specifications: { Material: "Solid Wood + Gold Leaf", Size: "King", Style: "Royal Ornate", Includes: "Full Set + 2 Mirrors", Warranty: "2 Years" },
    images: ["/images/beds/bed-golden-luxury.png"],
  },
  {
    id: "ALF-B10", name: "Walnut Padded King Bed", slug: "walnut-padded-king-bed",
    category: "beds", subcategory: "King Beds",
    price: 72000, originalPrice: 88000, badge: "Sale",
    inStock: true, stockQty: 6, rating: 4, reviewCount: 32, isFeatured: false, isNew: false,
    description: "Contemporary king bed with wide padded caramel headboard in solid walnut wood frame. Includes matching wardrobe and bedside tables.",
    colors: [{ name: "Walnut Brown", hex: "#8D6E63" }],
    specifications: { Material: "Sheesham Wood + Fabric", Size: "King", Headboard: "Wide Padded", Includes: "Wardrobe + Side Tables", Warranty: "2 Years" },
    images: ["/images/beds/bed-walnut-padded.png"],
  },
  {
    id: "ALF-B11", name: "Greyish Silver Luxury Bed", slug: "greyish-silver-luxury-bed",
    category: "beds", subcategory: "King Beds",
    price: 165000, originalPrice: 198000, badge: "Sale",
    inStock: true, stockQty: 3, rating: 5, reviewCount: 44, isFeatured: true, isNew: false,
    description: "Breathtaking silver and grey ornate king bed with carved frames and matching dressing mirrors. European-inspired grandeur for your master bedroom.",
    colors: [{ name: "Silver & Grey", hex: "#9E9E9E" }],
    specifications: { Material: "Solid Wood + Silver Finish", Size: "King", Style: "European Royal", Includes: "Full Set", Warranty: "2 Years" },
    images: ["/images/beds/bed-greyish-luxury.png"],
  },
  {
    id: "ALF-B12", name: "Vintage Long Back Bed", slug: "vintage-long-back-bed",
    category: "beds", subcategory: "King Beds",
    price: 118000, originalPrice: 142000, badge: "Sale",
    inStock: true, stockQty: 4, rating: 5, reviewCount: 39, isFeatured: true, isNew: false,
    description: "Cream and gold vintage-style king bed with tall ornate headboard and matching carved side pieces. Full bedroom set included.",
    colors: [{ name: "Cream & Gold", hex: "#EDE0C8" }],
    specifications: { Material: "Solid Wood + Gold Finish", Size: "King", Style: "Vintage Ornate", Includes: "Full Bedroom Set", Warranty: "2 Years" },
    images: ["/images/beds/bed-vintage-longback.png"],
  },
  {
    id: "ALF-B13", name: "White Classic Bed Set", slug: "white-classic-bed-set",
    category: "beds", subcategory: "King Beds",
    price: 135000, originalPrice: 162000, badge: "Sale",
    inStock: true, stockQty: 3, rating: 5, reviewCount: 51, isFeatured: true, isNew: false,
    description: "Pure white ornate classic bed with tall tufted headboard, carved side mirrors and matching dresser. A timeless bridal bedroom favourite.",
    colors: [{ name: "Pure White", hex: "#FAFAFA" }],
    specifications: { Material: "Solid Wood + White Finish", Size: "King", Style: "Classic Bridal", Includes: "Full Set + Mirrors", Warranty: "2 Years" },
    images: ["/images/beds/bed-white-classic.png"],
  },
  {
    id: "ALF-B14", name: "Teal Modern Bed Set", slug: "teal-modern-bed-set",
    category: "beds", subcategory: "King Beds",
    price: 88000, originalPrice: 0, badge: "New",
    inStock: true, stockQty: 5, rating: 5, reviewCount: 18, isFeatured: true, isNew: true,
    description: "Bold teal velvet king bed with geometric gold V-pattern headboard and matching teal bench. A modern showstopper for contemporary homes.",
    colors: [{ name: "Teal & Gold", hex: "#00695C" }],
    specifications: { Material: "Velvet + MDF + Gold", Size: "King", Style: "Modern Geometric", Includes: "Bed + Bench + Dresser", Warranty: "2 Years" },
    images: ["/images/beds/bed-teal-modern.png"],
  },
  {
    id: "ALF-B15", name: "Gold Headboard Luxury Set", slug: "gold-headboard-luxury-set",
    category: "beds", subcategory: "King Beds",
    price: 95000, originalPrice: 115000, badge: "Sale",
    inStock: true, stockQty: 4, rating: 5, reviewCount: 46, isFeatured: true, isNew: false,
    description: "Contemporary luxury king bed with wide padded gold-toned headboard and diamond pattern stitching. Includes matching bench and complete bedroom set.",
    colors: [{ name: "Gold Beige", hex: "#C8A532" }],
    specifications: { Material: "Velvet + Wood Frame", Size: "King", Headboard: "Diamond Tufted", Includes: "Complete Bedroom Set", Warranty: "2 Years" },
    images: ["/images/beds/bed-gold-headboard.png"],
  },

  // ── SOFAS ─────────────────────────────────────────────────────────────────
  {
    id: "ALF-S01", name: "Royal Gold Carved Sofa Set", slug: "royal-gold-carved-sofa",
    category: "sofas", subcategory: "Sofa Sets",
    price: 185000, originalPrice: 225000, badge: "Sale",
    inStock: true, stockQty: 3, rating: 5, reviewCount: 62, isFeatured: true, isNew: false,
    description: "Magnificent 5-seater royal sofa set with hand-carved gold frame and premium beige velvet upholstery. The pinnacle of luxury Pakistani craftsmanship.",
    colors: [{ name: "Gold & Beige", hex: "#C8A532" }],
    specifications: { Material: "Sheesham Wood + Gold + Velvet", Configuration: "3+1+1", Style: "Royal Carved", Cushions: "Included", Warranty: "2 Years" },
    images: ["/images/sofas/sofa-royal-gold.png"],
  },
  {
    id: "ALF-S02", name: "Cream Luxury Sofa Set", slug: "cream-luxury-sofa-set",
    category: "sofas", subcategory: "Sofa Sets",
    price: 155000, originalPrice: 185000, badge: "Sale",
    inStock: true, stockQty: 4, rating: 5, reviewCount: 54, isFeatured: true, isNew: false,
    description: "Premium 7-seater cream fabric sofa set with solid wood frame. Ultra-comfortable high-density foam seating with elegant minimalist design.",
    colors: [{ name: "Cream", hex: "#EDE0C8" }, { name: "Light Grey", hex: "#BDBDBD" }],
    specifications: { Material: "Solid Wood + Premium Fabric", Configuration: "3+2+1+1", Seating: "7 Persons", Warranty: "2 Years" },
    images: ["/images/sofas/sofa-cream-luxury.png"],
  },

  // ── CORNER SOFAS ──────────────────────────────────────────────────────────
  {
    id: "ALF-C01", name: "Gold Carved Corner Sofa", slug: "gold-carved-corner-sofa",
    category: "cornersofas", subcategory: "L-Shape",
    price: 245000, originalPrice: 295000, badge: "Sale",
    inStock: true, stockQty: 2, rating: 5, reviewCount: 41, isFeatured: true, isNew: false,
    description: "Opulent L-shaped corner sofa with hand-carved gold sheesham frame and premium beige velvet. Seats 6-7 in royal comfort. The ultimate statement piece.",
    colors: [{ name: "Gold & Beige Velvet", hex: "#C8A532" }],
    specifications: { Material: "Sheesham Wood + Gold + Velvet", Shape: "L-Shape", Seating: "6-7 Persons", Cushions: "8 Included", Warranty: "2 Years" },
    images: ["/images/cornersofas/corner-gold-carved.png"],
  },
  {
    id: "ALF-C02", name: "Mustard L-Shape Corner Sofa", slug: "mustard-lshape-corner-sofa",
    category: "cornersofas", subcategory: "L-Shape",
    price: 175000, originalPrice: 210000, badge: "Sale",
    inStock: true, stockQty: 3, rating: 5, reviewCount: 38, isFeatured: true, isNew: false,
    description: "Vibrant mustard yellow L-shape corner sofa with tufted button design and colourful printed cushions. Bold, cheerful and ultra-comfortable.",
    colors: [{ name: "Mustard Yellow", hex: "#F9A825" }],
    specifications: { Material: "Solid Wood + Velvet", Shape: "L-Shape", Seating: "6 Persons", Cushions: "5 Included", Warranty: "2 Years" },
    images: ["/images/cornersofas/corner-mustard-lshape.png"],
  },
  {
    id: "ALF-C03", name: "Grey & Black Corner Sofa", slug: "grey-black-corner-sofa",
    category: "cornersofas", subcategory: "L-Shape",
    price: 195000, originalPrice: 235000, badge: "Sale",
    inStock: true, stockQty: 3, rating: 4, reviewCount: 29, isFeatured: true, isNew: false,
    description: "Modern grey and black L-shape corner sofa with printed cushions. Contemporary design with solid hardwood frame. Seats 7-8 comfortably.",
    colors: [{ name: "Grey & Black", hex: "#37474F" }],
    specifications: { Material: "Hardwood + Woven Fabric", Shape: "L-Shape", Seating: "7-8 Persons", Cushions: "7 Included", Warranty: "2 Years" },
    images: ["/images/cornersofas/corner-grey-black.png"],
  },
  {
    id: "ALF-C04", name: "U-Shape Brown Corner Sofa", slug: "ushape-brown-corner-sofa",
    category: "cornersofas", subcategory: "U-Shape",
    price: 320000, originalPrice: 385000, badge: "Sale",
    inStock: true, stockQty: 2, rating: 5, reviewCount: 33, isFeatured: true, isNew: false,
    description: "Massive U-shape corner sofa in warm brown woven fabric with matching centre table. Seats 10+ people. The ultimate family living room centrepiece.",
    colors: [{ name: "Warm Brown", hex: "#8D6E63" }],
    specifications: { Material: "Hardwood + Woven Fabric", Shape: "U-Shape", Seating: "10+ Persons", Includes: "Centre Table", Cushions: "10 Included", Warranty: "2 Years" },
    images: ["/images/cornersofas/corner-ushape-brown.png"],
  },
  {
    id: "ALF-C05", name: "Beige L-Shape Corner Sofa", slug: "beige-lshape-corner-sofa",
    category: "cornersofas", subcategory: "L-Shape",
    price: 165000, originalPrice: 198000, badge: "Sale",
    inStock: true, stockQty: 4, rating: 4, reviewCount: 22, isFeatured: false, isNew: false,
    description: "Classic beige L-shape corner sofa with decorative gold border trim and solid armrests. Comfortable and stylish for any living room.",
    colors: [{ name: "Beige & Gold", hex: "#EDE0C8" }],
    specifications: { Material: "Solid Wood + Fabric", Shape: "L-Shape", Seating: "6 Persons", Cushions: "6 Included", Warranty: "2 Years" },
    images: ["/images/cornersofas/corner-beige-lshape.png"],
  },

  // ── ACCENT CHAIRS ─────────────────────────────────────────────────────────
  {
    id: "ALF-A01", name: "Black Chaise Lounge", slug: "black-chaise-lounge",
    category: "accent", subcategory: "Chaise Lounges",
    price: 35000, originalPrice: 42000, badge: "Sale",
    inStock: true, stockQty: 5, rating: 4, reviewCount: 27, isFeatured: false, isNew: false,
    description: "Sleek black lacquered chaise lounge with white cushioned seat and gold claw feet. A sophisticated accent piece for bedrooms or lounges.",
    colors: [{ name: "Black & White", hex: "#212121" }],
    specifications: { Material: "Wood + Fabric", Length: "160 cm", Legs: "Gold Claw", Warranty: "1 Year" },
    images: ["/images/accent/accent-black-chaise.png"],
  },
  {
    id: "ALF-A02", name: "Teal Carved Accent Chairs", slug: "teal-carved-accent-chairs",
    category: "accent", subcategory: "Accent Chairs",
    price: 45000, originalPrice: 55000, badge: "Sale",
    inStock: true, stockQty: 4, rating: 5, reviewCount: 35, isFeatured: true, isNew: false,
    description: "Pair of elegant teal velvet accent chairs with ornate silver carved frames. Sold as a pair with matching centre table. A showroom statement.",
    colors: [{ name: "Teal & Silver", hex: "#00695C" }],
    specifications: { Material: "Solid Wood + Velvet", Includes: "2 Chairs + Centre Table", Style: "Carved Royal", Warranty: "1 Year" },
    images: ["/images/accent/accent-teal-carved.png"],
  },
  {
    id: "ALF-A03", name: "Cream Modern Accent Chairs", slug: "cream-modern-accent-chairs",
    category: "accent", subcategory: "Accent Chairs",
    price: 28500, originalPrice: 35000, badge: "Sale",
    inStock: true, stockQty: 6, rating: 5, reviewCount: 42, isFeatured: true, isNew: false,
    description: "Contemporary pair of cream shell-back accent chairs with black hairpin legs and matching marble-top side table. Modern minimalist elegance.",
    colors: [{ name: "Cream & Black", hex: "#EDE0C8" }],
    specifications: { Material: "Fabric + Metal Legs", Includes: "2 Chairs + Side Table", Style: "Modern Minimalist", Warranty: "1 Year" },
    images: ["/images/accent/accent-cream-modern.png"],
  },
  {
    id: "ALF-A04", name: "Wingback Floral Chairs", slug: "wingback-floral-chairs",
    category: "accent", subcategory: "Accent Chairs",
    price: 38000, originalPrice: 46000, badge: "Sale",
    inStock: true, stockQty: 4, rating: 4, reviewCount: 19, isFeatured: false, isNew: false,
    description: "Classic wingback chairs in floral cream fabric with carved black and gold wooden frame. Pair includes a matching centre table. Timeless elegance.",
    colors: [{ name: "Cream Floral", hex: "#EDE0C8" }],
    specifications: { Material: "Solid Wood + Fabric", Style: "Wingback", Includes: "2 Chairs + Table", Warranty: "1 Year" },
    images: ["/images/accent/accent-wingback-floral.png"],
  },
  {
    id: "ALF-A05", name: "Colourful Fabric Accent Chairs", slug: "colorful-fabric-accent-chairs",
    category: "accent", subcategory: "Accent Chairs",
    price: 22000, originalPrice: 0, badge: "New",
    inStock: true, stockQty: 8, rating: 4, reviewCount: 11, isFeatured: false, isNew: true,
    description: "Fun and vibrant barrel accent chairs in colourful ethnic fabric prints. Available in multiple patterns. Perfect to add a pop of colour to any room.",
    colors: [{ name: "Multi Colour", hex: "#E91E63" }, { name: "Blue Pattern", hex: "#1565C0" }],
    specifications: { Material: "Solid Frame + Fabric", Style: "Barrel / Ethnic", Colours: "Multiple Available", Warranty: "1 Year" },
    images: ["/images/accent/accent-colorful-fabric.png"],
  },
  {
    id: "ALF-A06", name: "Cream Gold Wingback Set", slug: "cream-gold-wingback-set",
    category: "accent", subcategory: "Accent Chairs",
    price: 52000, originalPrice: 63000, badge: "Sale",
    inStock: true, stockQty: 3, rating: 5, reviewCount: 31, isFeatured: true, isNew: false,
    description: "Luxurious pair of cream damask wingback chairs with gold carved sheesham wood frame and matching ottoman. Royal comfort for any reading room or lounge.",
    colors: [{ name: "Cream & Gold", hex: "#EDE0C8" }],
    specifications: { Material: "Sheesham Wood + Damask Fabric", Includes: "2 Chairs + Ottoman", Style: "Royal Wingback", Warranty: "1 Year" },
    images: ["/images/accent/accent-cream-gold.png"],
  },
];

export default products;
